CREATE DATABASE IF NOT EXISTS asn;
USE asn;

CREATE TABLE IF NOT EXISTS empleado (
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    salario DECIMAL(10,2) DEFAULT NULL,
    area VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;